In [8]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr+10)

[11 12 13 14]


In [9]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
print(arr.ndim)

1


In [11]:
## arr.shape

print(arr.shape)



(4,)


In [12]:
## arr.size
print(arr.size)

4


In [14]:
## dtype

print(arr.dtype)

int64


In [15]:
marks = (10,20,30,40)
print(type(marks))

<class 'tuple'>


In [16]:
arr2 = np.array(marks)
print(type(arr2))

<class 'numpy.ndarray'>


In [22]:
zero_arr = np.zeros(6)
print(zero_arr)
print(zero_arr.dtype)

zero_arr = zero_arr.astype(int)
print(zero_arr)
print(type(zero_arr))
print(zero_arr.dtype)

[0. 0. 0. 0. 0. 0.]
float64
[0 0 0 0 0 0]
<class 'numpy.ndarray'>
int64


In [24]:
one_arr = np.ones((3,2))
print(one_arr)
print(one_arr.dtype)

one_arr = one_arr.astype(int)
print(one_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64
[[1 1]
 [1 1]
 [1 1]]


In [25]:
garbage_arr = np.empty(8)
print(garbage_arr)

[3.31529723e-315 0.00000000e+000 1.39067116e-309 1.10835559e-301
 3.48128693e-308 4.54319519e-311 4.21050058e-297 2.13517428e-314]


In [30]:
## rand()

arr1 = np.random.rand(5) ## between 0 and 1
print(arr1)

[0.70496614 0.92924432 0.17124942 0.52057313 0.028802  ]


In [36]:
## randint()
arr2 = np.random.randint(1,20,size = 5)
print(arr2)

[19  2  1  8  1]


In [37]:
## randn()
arr3 = np.random.randn(8)
print(arr3)

[ 0.05039611 -0.23411106  0.72052741  1.11409215  0.11860593  1.26393582
  0.3799338   1.94007503]


In [41]:
## array slicing

arr4 = np.array([1,2,3,4,5,6,7])

print(arr4)
print(arr4[1:5])

print(arr4[1:])
print(arr4[:5])


[1 2 3 4 5 6 7]
[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4 5]


In [48]:
mat =  np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(mat)
print(mat.size)
print(mat.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


In [49]:
print(mat[1,0:2])

[4 5]


In [50]:
print(mat[:,1])

[2 5 8]


In [51]:
print(mat[1:,1:])

[[5 6]
 [8 9]]


In [53]:
arr5 = np.array([1,2,3,4,5])
arr5[::-1]


array([5, 4, 3, 2, 1])

In [54]:
## reshaping and flatenning

arr6 = np.array([1,2,3,4,5,6])
print(arr6.reshape(3,2))


[[1 2]
 [3 4]
 [5 6]]


In [55]:
arr6.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr7 = np.array([[1,2,3],[4,5,6]])

print(arr7.flatten())



[1 2 3 4 5 6]


In [59]:
arr8 = arr7.ravel()
print(arr8)

arr8[0]=10
print(arr7)
print(arr8)


[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]
[10  2  3  4  5  6]


In [61]:
mat1 = np.array([[1,2,3,4],[5,6,7,8]])

arr9 = mat1.flatten()
print(arr9)

arr9[0]=10
print(arr9)
print(mat1)

[1 2 3 4 5 6 7 8]
[10  2  3  4  5  6  7  8]
[[1 2 3 4]
 [5 6 7 8]]


In [63]:
## fancy indexing

arr10= np.array([100,200,300,400])
print(arr10[[0,2]])

[100 300]


In [65]:
## boolean indexing

arr11 = np.array([10,2,30,4,50,6])

marks = arr11>10
print(marks)

print(arr11[marks])

[False False  True False  True False]
[30 50]


In [70]:
mat4 = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(mat4[(mat4>4) & (mat4<=8)])

[5 6 7 8]


In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [72]:
mat3 = np.array([[1,2,3,4],
                [5,6,7,8]])

print(np.hsplit(mat3,2))
print(np.vsplit(mat3,2))



[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [73]:
mat = np.array([[1,2,3],
                [4,5,6]])
print(np.sum(mat, axis=0))
print(np.sum(mat, axis=1))

[5 7 9]
[ 6 15]


In [74]:
arr = np.array([40,10,30,20])

print(np.where(arr>20))

(array([0, 2]),)
